SELECT * FROM International_Breweries ib;

-- SECTION A: PROFIT ANALYSIS

-- Q1

SELECT DISTINCT YEARS FROM International_Breweries ib;

SELECT BRANDS, SUM(PROFIT) AS PROFIT, COUNTRIES 
FROM International_Breweries ib
GROUP BY BRANDS
ORDER BY 2 DESC;

-- Q2

SELECT DISTINCT("REGION ") FROM International_Breweries ib;

SELECT "REGION " , SUM(PROFIT) AS "TOTAL PROFIT" 
FROM International_Breweries ib 
GROUP BY "REGION " 
ORDER BY 2 DESC;

-- Q3

SELECT COUNTRIES, SUM(PROFIT) AS "HIGHEST PROFIT"  
FROM International_Breweries ib 
WHERE YEARS = 2019
GROUP BY COUNTRIES 
ORDER BY 2 DESC 
LIMIT 1;

-- Q4

SELECT YEARS, SUM(PROFIT) AS "HIGHEST PROFIT" 
FROM International_Breweries ib 
GROUP BY YEARS  
ORDER BY 2 DESC
LIMIT 1;

-- Q5

SELECT MONTHS , SUM(PROFIT) AS "LEAST PROFIT" 
FROM International_Breweries ib 
GROUP BY MONTHS  
ORDER BY 2
LIMIT 1;

-- Q6

SELECT BRANDS ,MONTHS,YEARS , SUM(PROFIT) AS PROFIT 
FROM International_Breweries ib 
WHERE MONTHS ='December' AND YEARS = 2018
GROUP BY BRANDS 
ORDER BY 4
LIMIT 1;

-- Q7

SELECT MONTHS, ROUND((CAST (SUM(PROFIT) AS DECIMAL)/30020250) * 100, 4) AS "PROFIT PERCENTAGE"
FROM International_Breweries ib 
WHERE YEARS = 2019
GROUP BY 1;

-- Q8

SELECT BRANDS, SUM(PROFIT) AS "HIGHEST PROFIT" 
FROM International_Breweries ib 
WHERE COUNTRIES = "Senegal" 
GROUP BY BRANDS
ORDER BY 2 DESC 
LIMIT 1;

-- SECTION B: BRAND ANALYSIS

-- Q1

SELECT BRANDS,SUM(QUANTITY) AS "QUANTITY CONSUMED"  
FROM International_Breweries ib
WHERE YEARS IN(2018,2019)
GROUP by BRANDS 
ORDER by 2 DESC 
LIMIT 3;

-- Q2

SELECT BRANDS, SUM(QUANTITY) AS "TOP 2 CHOICE" 
FROM International_Breweries ib
WHERE COUNTRIES = "Ghana"  
GROUP by BRANDS 
ORDER by 2 DESC 
LIMIT 2;

-- Q3

SELECT BRANDS, SUM(QUANTITY) AS "QUANTITY CONSUMED", COUNTRIES, YEARS 
FROM International_Breweries ib 
WHERE "REGION "  = "west" 
GROUP BY BRANDS 
ORDER BY 2;

-- Q4

SELECT BRANDS, SUM(QUANTITY) AS "QUANTITY CONSUMED"  
FROM International_Breweries ib 
WHERE YEARS IN (2018,2019)
GROUP BY BRANDS 
ORDER BY 2 DESC 
LIMIT 1;

-- Q5

SELECT BRANDS, SUM(QUANTITY) AS "QUANTITY CONSUMED"  
FROM International_Breweries ib 
WHERE COUNTRIES = "Nigeria" AND YEARS =2019
GROUP BY BRANDS 
ORDER BY 2 DESC 
LIMIT 1;

-- Q6

SELECT BRANDS, SUM(QUANTITY) AS "QUANTITY CONSUMED", COUNTRIES  
FROM International_Breweries ib 
WHERE "REGION " = "southsouth" 
GROUP BY BRANDS 
ORDER BY 2 DESC;

-- Q7

SELECT DISTINCT(BRANDS), SUM(QUANTITY) AS "QUANTITY CONSUMED" FROM International_Breweries ib 
WHERE COUNTRIES = "Nigeria"
ORDER BY 1;

-- Q8

SELECT "REGION ", SUM(QUANTITY) AS "QUANTITY CONSUMED" 
FROM International_Breweries ib 
WHERE BRANDS = "budweiser" AND COUNTRIES = "Nigeria"
GROUP BY 1
ORDER BY 2 DESC;

-- Q9

SELECT "REGION ", SUM(QUANTITY) AS "QUANTITY CONSUMED"  
FROM International_Breweries ib 
WHERE COUNTRIES = "Nigeria" AND BRANDS = "budweiser" AND YEARS = 2019
GROUP BY 1
ORDER BY 2 DESC;

-- SECTION C: COUNTRIES ANALYSIS

-- Q1

SELECT COUNTRIES , SUM(QUANTITY) AS "QUANTITY CONSUMED"  
FROM International_Breweries ib 
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 1;

-- Q2

SELECT SALES_REP , SUM(COST) AS "HIGHEST SALES COST"  
FROM International_Breweries ib 
WHERE BRANDS = "budweiser" AND COUNTRIES = "Senegal"  
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 1;

-- Q3

SELECT COUNTRIES  , SUM(PROFIT) AS "HIGHEST PROFIT"  
FROM International_Breweries ib 
WHERE YEARS  = 2019 AND MONTHS IN("September","October","November","December")
GROUP BY 1
ORDER BY 2 DESC 
LIMIT 1;

